### ISSUE TITLE
Deep link to the CR for module does not work

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/kyma-dashboard#170]
**Description**

The Links points to the ModuleTemplates

**Expected result**

Should point to the path mentioned in status

**Actual result**

**Steps to reproduce**

**Troubleshooting**

<img width="443" alt="image" src="https://github.com/kyma-project/kyma-dashboard/assets/478866/4b31562a-dcd2-413f-8044-ed2b371505e7">

**Comment by mrCherry97** [comment]
Currently works as expected
