### ISSUE TITLE
Move build pipeline and tests to github actions and ADO

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma-dashboard#306]
**Description**
There is a way to build images using reusable workflow from test-infra.

Examples: 
- https://github.com/dekiel/test-infra/blob/main/.github/workflows/test-out-org.yml
- https://github.com/kyma-project/test-infra/blob/main/.github/workflows/pull-build-oidc-token-verifier.yml

Remember about permissions. Example:
: https://github.com/dekiel/test-infra/blob/ada722b56dc5617e15a569241ab4c423fa00b88b/.github/workflows/test-out-org.yml#L12C1-L15C1

**Reasons**

Prow infrastructure is going to be shutdown and all Kyma teams are asked to migrate.

**Acceptance criteria**
Builds:
- [x] busola-local build is moved to GithubActions
https://github.com/kyma-project/busola/pull/2971
https://github.com/kyma-project/busola/pull/2972
https://github.com/kyma-project/busola/pull/2974
https://github.com/kyma-project/busola/pull/2976
- [x] remove from test-infra: 
https://github.com/kyma-project/test-infra/pull/11027
- [x] busola-web build is moved to GithubActions
https://github.com/kyma-project/busola/pull/3124
- [x] remove from test-infra
https://github.com/kyma-project/test-infra/pull/11757
- [x] busola-backend build is moved to GithubActions
https://github.com/kyma-project/busola/pull/3124
- [x] remove from test-infra
https://github.com/kyma-project/test-infra/pull/11757
- [x] kyma-dashboard-dev build is moved to GithubActions
https://github.com/kyma-project/kyma-dashboard/pull/308
https://github.com/kyma-project/kyma-dashboard/pull/314
https://github.com/kyma-project/kyma-dashboard/pull/317
https://github.com/kyma-project/kyma-dashboard/pull/328
https://github.com/kyma-project/kyma-dashboard/pull/327
https://github.com/kyma-project/kyma-dashboard/pull/357
- [x] kyma-dashboard-dev URL to the registry is adjusted
https://github.com/kyma-project/kyma-dashboard/pull/355
- [x] remove from test-infra
https://github.com/kyma-project/test-infra/pull/11757
- [x] kyma-dashboard-stage build is moved to GithubActions
https://github.com/kyma-project/kyma-dashboard/pull/355
- [x] remove from test-infra
https://github.com/kyma-project/test-infra/pull/11757
https://github.com/kyma-project/test-infra/pull/11757
- [x] kyma-dashboard-prod build is moved to GithubActions
https://github.com/kyma-project/kyma-dashboard/pull/355
https://github.com/kyma-project/kyma-dashboard/pull/357
- [x] remove from test-infra
https://github.com/kyma-project/test-infra/pull/11757

Tests:
- [x] busola-integration-namespace
https://github.com/kyma-project/busola/pull/2981
- [x] remove from test-infra
https://github.com/kyma-project/test-infra/pull/11171
- [x] busola-integration-cluster
https://github.com/kyma-project/busola/pull/3033
- [x] remove from test-infra
https://github.com/kyma-project/test-infra/pull/11268
- [x] busola-lighthouse
https://github.com/kyma-project/busola/pull/3033
- [x] remove from test-infra
https://github.com/kyma-project/test-infra/pull/11268
- [x] kyma-dashboard-integration
https://github.com/kyma-project/kyma-dashboard/pull/340
- [x] remove from test-infra
https://github.com/kyma-project/test-infra/pull/11268
- [x] kyma-dashboard-smoke-stage
https://github.com/kyma-project/kyma-dashboard/pull/345
- [x] remove from test-infra
https://github.com/kyma-project/test-infra/pull/11268
- [x] kyma-dashboard-smoke-prod
https://github.com/kyma-project/kyma-dashboard/pull/345
- [x] remove from test-infra
https://github.com/kyma-project/test-infra/pull/11268

- [x] workflow for checking if there is any changes in extensibility and `extensions/statics/wizards.yaml` should be regenerated
https://github.com/kyma-project/kyma-dashboard/pull/336

- [ ] remove `dockerfile.*.builder` from kyma-dashboard
https://github.com/kyma-project/kyma-dashboard/pull/368

Settings:
- [ ] all build jobs are added as required in repo settings
- [ ] Tide is settled as unmanaged for busola and kyma-dashboard repo
- [ ] Automerge is set
- [ ] Passing all of the checks to merge is set

**Comment by dbadura** [comment]
I would also remove the duplicate images:
- https://github.com/kyma-project/kyma-dashboard/blob/main/Dockerfile.local
- https://github.com/kyma-project/kyma-dashboard/blob/main/Dockerfile.local.builder
and leave the one without `builder`.

**Comment by mrCherry97** [comment]
tide and auto-merge need to be done as follow-up, after removing tide
