### ISSUE TITLE
The $readableTimestamp doesn't display the timestamp in the Busola extension as expected

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-project/kyma-dashboard#44]
**Description**

I was [creating a busola extension](https://github.com/kyma-project/kyma/pull/16381) for Subscriptions and following your [jsonata guide](https://github.com/kyma-project/busola/blob/main/docs/extensibility/jsonata.md#readabletimestamptimestamp) and copy-pasted exactly the same code:
```
- source: '$readableTimestamp($item.lastTransitionTime)'
   name: status.conditions.lastTransitionTime
```

but recently it started behaving weirdly:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/15933100/209142211-e4e87def-bbac-4928-9443-e14db8aef7c3.png">

The timestamp, which I have is: `2022-12-22T10:40:43Z` and it was working in the past and only recently it broke.

**Comment by mrCherry97** [comment]
@VladislavPaskar fix is merged and pushed to prod, so now it should work properly.
