### ISSUE TITLE
Add a posibility to disable an input in the Busola extentions

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-project/kyma-dashboard#45]
**Description**

As a Kyma developer who writes a Busola extension I would like to be able to make certain inputs disabled. There is already a similar behaviour in the Subscription tab:
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/15933100/209143013-9916c230-6fee-4a66-8b6d-65ea0c821c88.png">

**Comment by mrCherry97** [comment]
Hi @VladislavPaskar 
We introduce `readOnly` flag for `widget: Text`
https://github.com/kyma-project/busola/blob/main/docs/extensibility/form-section.md#text
Changes are actually on dev, on following days we will push it to stage and prod.
