### ISSUE TITLE
Add defaultValue for a text input in Busola extensions

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-project/kyma-dashboard#49]
**Description**

As a developer who works with Busola extension, I want to be able to set default value for enumed text Input. As you can see on the screenshot, I have a text input with two possible values. I would like to be able to pre-select one of them, so that once you open the form view, the selected enum value would be pre-selected. 

<img width="716" alt="image" src="https://user-images.githubusercontent.com/15933100/209327224-7f3f140f-777d-4772-841a-aefa99cf6c3e.png">

Note: `defaultValue` from [this guide](https://github.com/kyma-project/busola/blob/c1cbb6753c7c8cb0b45a75bb2a1ed9363707670e/docs/extensibility/form-section.md#item-parameters-1) doesn't work.

**Comment by mrCherry97** [comment]
Hi @VladislavPaskar this is not variable field so, guide what you mentioned couldn't work. We have [presets functionality](https://github.com/kyma-project/busola/blob/c1cbb6753c7c8cb0b45a75bb2a1ed9363707670e/docs/extensibility/presets-section.md) for case like this. 

Some examples how we are using it:
https://github.com/kyma-project/kyma-dashboard/blob/main/extensions/istio/gateways.yaml#L185 
https://github.com/kyma-project/kyma-dashboard/blob/main/extensions/gateway/apirules.yaml#L305

Please check if it could help you, if not please reopen the issue.

**Comment by VladislavPaskar** [comment]
> Hi @VladislavPaskar this is not variable field so, guide what you mentioned couldn't work. We have [presets functionality](https://github.com/kyma-project/busola/blob/c1cbb6753c7c8cb0b45a75bb2a1ed9363707670e/docs/extensibility/presets-section.md) for case like this.
> 
> Some examples how we are using it: https://github.com/kyma-project/kyma-dashboard/blob/main/extensions/istio/gateways.yaml#L185 https://github.com/kyma-project/kyma-dashboard/blob/main/extensions/gateway/apirules.yaml#L305
> 
> Please check if it could help you, if not please reopen the issue.

@mrCherry97 thank you, it worked with the presets!
