### ISSUE TITLE
Support or deactivate Subsription creation form in the Function's tab

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/kyma-dashboard#66]
**Description**

According to [this issue](https://github.com/kyma-project/kyma/issues/16501), Busola is currently not supporting the creation of the v1alpha2 Subscription from the Function's tab.

**Expected behaviour**

When the v1alpha2 Version [will be released](https://github.com/kyma-project/kyma/issues/16251), the mentioned create form should be either:
1) removed

**OR**

2) support the creation of the v1alpha2 Subscription without any errors, as it was working for the v1alpha1 version.

**Comment by mfaizanse** [comment]
Related: https://github.com/kyma-project/busola/issues/2371

**Comment by friedrichwilken** [comment]
@valentinvieriu Since kyma `2.12` is release on OSS and will be released on SKR this weekend is there any updates?

**Comment by mfaizanse** [comment]
PR: https://github.com/kyma-project/kyma-dashboard/pull/155

**Comment by grischperl** [comment]
The v1alpha2 version is supported by Busola (verified [here](https://github.com/kyma-project/kyma/issues/16984)), as long as the subscription is created from the Subscriptions tab. 

As mentioned [here](https://github.com/kyma-project/kyma/issues/16501#issuecomment-1450522482) the ability to create subscriptions from the Functions tab will come back once support for Subscription v1alpha1 is removed after 6 months.

**Comment by mrCherry97** [comment]
@kyma-project/otters currently are taking care of this extension. As I remember they adjusted that.
